Refactor deploy workflow: switch to self-hosted runner, replace SSH deployment with Docker-based approach, and add image cleanup step

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -33,28 +33,51 @@ jobs:
             -Djib.to.auth.username=${{ secrets.GH_USERNAME }} \
             -Djib.to.auth.password=${{ secrets.GH_TOKEN }}
 
-  deploy-to-production:
-    name: Deploy to Production
+  deploy:
     needs: build-and-push
-    runs-on: ubuntu-latest
+    runs-on:
+      group: cyclops
+      labels: self-hosted
     steps:
-      - name: SSH Remote Commands
-        uses: appleboy/ssh-action@v1.0.3
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v3
         with:
-          host: ${{ secrets.DEV_SSH_URL }}
-          username: ${{ secrets.DEV_SSH_USERNAME }}
-          key: ${{ secrets.DEV_SSH_PK }}
-          port: ${{ secrets.DEV_SSH_PORT }}
-          script: |
-            echo "Starting deployment..."
-            # Log in using secrets directly
-            echo "${{ secrets.GH_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.GH_USERNAME }} --password-stdin
-            
-            # Pull the specific version
-            docker pull ${{ env.IMAGE_NAME }}:0.0.1-SNAPSHOT
-            
-            # Restart the service
-            docker compose up -d backend
-            
-            docker logout ${{ env.REGISTRY }}
-            echo "Deployment finished successfully."
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GH_TOKEN }}
+
+      - name: Pull latest image
+        run: docker pull ghcr.io/entwickler-elf/phoenix-java:latest
+
+      - name: Stop and remove existing container
+        run: |
+          # Stop and remove existing container
+          docker stop phoenix-java || true
+          docker rm phoenix-java || true
+
+          # Optional: Find any other container using port 80 and stop it
+            PORT_OWNER=$(docker ps -q --filter "publish=8090")
+            if [ ! -z "$PORT_OWNER" ]; then
+              echo "Stopping container $PORT_OWNER which is using port 8090"
+              docker stop $PORT_OWNER || true
+            fi
+
+
+
+      - name: Run new container
+        run: |
+          docker run -d \
+            --name phoenix-java \
+            --restart always \
+            -p 80:8090 \
+            ghcr.io/entwickler-elf/phoenix-java:${{ env.IMAGE_TAG }}
+
+          sleep 5
+          if [ "$(docker inspect -f '{{.State.Running}}' phoenix-java)" != "true" ]; then
+            echo "Container failed to start. Logs:"
+            docker logs phoenix-java
+            exit 1
+          fi
+
+      - name: Cleanup old images
+        run: docker image prune -f
